services:
  db:
    image: postgres
    restart: always
    networks:
      - pg
    env_file:
      - ./postgres/.env

  adminer:
    build: ./pgadmin
    restart: always
    networks:
      - pg
    ports:
      - "5050:80"
    env_file:
      - ./pgadmin/.env

networks:
  pg:
