services:
  db:
    # image: postgres:17
    build: ./postgres
    restart: always
    networks:
      - pg
    env_file:
      - ./postgres/.env
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d piscineds -U alorain"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  # initialize:
  #   build: ./postgres
  #   networks:
  #     - pg
  #   env_file:
  #     - ./postgres/.env
  #   depends_on:
  #     db:
  #       condition: service_healthy

 

  adminer:
    build: ./pgadmin
    restart: always
    networks:
      - pg
    ports:
      - "5050:80"
    env_file:
      - ./pgadmin/.env
    depends_on:
      - db

networks:
  pg:
